version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env.mongo
    volumes:
      - mongodb:/data/db
  fastapi_shop:
    build:
      context: .
    ports:
      - "8989:8989"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env.project
    volumes:
      - static_volume:/code/static
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - fastapi_shop
  celery:
    build:
      context: .
    command: celery -A celery_tasks:celery worker --loglevel=INFO --pool=solo
    depends_on:
      - redis
      - rabbitmq
      - mongo
    env_file:
      - .env.project
    volumes:
      - static_volume:/code/static
  celery-beat:
    build:
      context: .
    command: celery -A celery_tasks:celery beat --loglevel=INFO
    depends_on:
      - redis
      - rabbitmq
      - mongo
      - celery
    env_file:
      - .env.project
    volumes:
      - static_volume:/code/static
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  static_volume:
  mongodb: